version: '3.8'
services:
  frontend:
    image: wmdeneth/frontend-app:latest
    ports:
      - "80:3000"
    environment:
      - REACT_APP_API_URL=http://100.53.63.93:4000
    restart: always

  backend:
    image: wmdeneth/backend-app:latest
    ports:
      - "4000:4000"
